apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: la3uwis0o-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: la3uwis0o-python 
  name: la3uwis0o-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: la3uwis0o-python 
